### ISSUE TITLE
Add support for OPTIONS-provided username and password

### ISSUE THREAD

**Issue by jdunck** [django-pylibmc/django-pylibmc#10]
Presently:

    def __init__(self, server, params, username=None, password=None):
        ...
        self._username = os.environ.get('MEMCACHE_USERNAME', username)

Proposed:

    def __init__(self, server, params, username=None, password=None):
        ...
        self._username = os.environ.get('MEMCACHE_USERNAME', username or params.get('username'))

And the same for password.

It seems strange to me to have to poke things into environment from settings.

**Comment by jwhitlock** [comment]
Fixed back in https://github.com/django-pylibmc/django-pylibmc/commit/e1c265f5f2fcd2f13eeafff7f5ca13a6887f9c89
