### ISSUE TITLE
Default timeout override

### ISSUE THREAD

**Issue by nicorevin** [django-pylibmc/django-pylibmc#12]
Hi!

Noticed that cache never expires when I do `cache.set('foo','bar')`

And indeed:
```python
>>> cache._get_memcache_timeout()
500
>>> cache.default_timeout
500
>>> def whoaaa(timeout=None):
...     return cache._get_memcache_timeout(timeout)
... 
>>> whoaaa()                                       
0
```
Have a look at [set](https://github.com/jbalogh/django-pylibmc/blob/fe5dc7d516b46eaebb25144fca7c12bed09e5305/django_pylibmc/memcached.py#L124) and [add](https://github.com/jbalogh/django-pylibmc/blob/fe5dc7d516b46eaebb25144fca7c12bed09e5305/django_pylibmc/memcached.py#L103y).
Is this behavior intentional? I thought that the default [TIMEOUT](https://docs.djangoproject.com/en/dev/ref/settings/#timeout) should be respected.

**Comment by jwhitlock** [comment]
Closed w/ 95e4ea45e3
