### ISSUE TITLE
Inspect Server Error On Set Exceptions

### ISSUE THREAD

**Issue by jamescarr** [django-pylibmc/django-pylibmc#22]
When we switched over to twemproxy I started getting a lot of exceptions whenever a backend server was unavailable. 

The cause was this line: https://github.com/jbalogh/django-pylibmc/blob/master/django_pylibmc/memcached.py#L131

len(value) will throw a TypeError if value is an int.

**Comment by jwhitlock** [comment]
It looks like this code changed w/ https://github.com/django-pylibmc/django-pylibmc/commit/6296b26bfc216032a792e4870bff63d7da332d09

https://github.com/django-pylibmc/django-pylibmc/blob/master/django_pylibmc/memcached.py#L131

```python
try:
    return self._cache.set(key, value,
                           self._get_memcache_timeout(timeout),
                           **COMPRESS_KWARGS)
except pylibmc.ServerError:
    log.error('ServerError saving %s (%d bytes)' % (key, len(str(value))),
              exc_info=True)
    return False
```

Can this ticket be closed?

**Comment by jwhitlock** [comment]
It looks like this was left open after the code was committed.  Closing.
