### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by reverie** [django-pylibmc/django-pylibmc#28]
This package currently only supports Python 2. Python 3 support would be great!

**Comment by meshy** [comment]
It looks as though there has been some progress made here: https://github.com/jbalogh/django-pylibmc/pull/16

**Comment by meshy** [comment]
Not to mention https://github.com/jbalogh/django-pylibmc/pull/30!

**Comment by n49ryan** [comment]
+1

**Comment by rexposadas** [comment]
I had to make further modifications in order for it to run on python 3.4 and Django 1.7.

https://github.com/rexposadas/django-pylibmc/commit/c458e2d2711d6aa9610a3622eb21938295d39af6

Here is an [SO question](http://stackoverflow.com/questions/29189899/django-pylibmc-complains-under-django-1-7-and-python-3-4) I opened which triggered me to fork the repo and make the change.

**Comment by jwhitlock** [comment]
Python 3 support added with #30
