### ISSUE TITLE
[feature request] persistent connection

### ISSUE THREAD

**Issue by max-posedon** [django-pylibmc/django-pylibmc#6]
Hi!

What about adding persistent connection to memcached? I tried following wrapper, which disables "close", and everything is working on my stand. But I don't believe that it could be so simple.

Could you help me understand, where is the problem with such idea?

P.S. My test suit could be found here: https://github.com/max-posedon/djmemd

<pre>
from django_pylibmc.memcached import PyLibMCCache as DjangoPyLibMCCache

class DjangoPyLibMCCache2(DjangoPyLibMCCache):
    def close(self, **kwargs):
        pass
</pre>

**Comment by edmorley** [comment]
The upstream Django fix for this seems to have stalled again:
https://github.com/django/django/pull/4866
https://code.djangoproject.com/ticket/11331

At the moment I'm using the workaround mentioned here:
https://devcenter.heroku.com/articles/memcachier#django

However as the OP above suggests, we could just work around this in django-pylibmc similar to how django-bmemcached did:
https://github.com/jaysonsantos/django-bmemcached/pull/8

Would you accept such a PR? :-)

**Comment by edmorley** [comment]
I fixed this upstream in Django 1.11:
django/django/pull/7200

When I get a chance I'll add a fix to django-pylibmc for Django 1.18/1.10.

**Comment by edmorley** [comment]
I have a fix for this locally which I'll open a PR for once the new tests in #49 are merged (one of the new tests covers this case).
